// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6_qROB6sOwKn4EHnR0VxyaXqnk7fzuQE',
    appId: '1:366516581058:web:266a9f2fc52e5dd2ea415b',
    messagingSenderId: '366516581058',
    projectId: 'flutter-stock-app',
    authDomain: 'flutter-stock-app.firebaseapp.com',
    storageBucket: 'flutter-stock-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-ilOAqqgYJKtOxDcWfQWztvM_IxW9R-A',
    appId: '1:366516581058:android:17702006e93de02eea415b',
    messagingSenderId: '366516581058',
    projectId: 'flutter-stock-app',
    storageBucket: 'flutter-stock-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADs2KtLzScpYS4RY4eyh6B2j0UJOhu_2s',
    appId: '1:366516581058:ios:7833a5a39fbb8a4cea415b',
    messagingSenderId: '366516581058',
    projectId: 'flutter-stock-app',
    storageBucket: 'flutter-stock-app.appspot.com',
    iosClientId: '366516581058-kip3t9ejc0d1i1q2i64e3ncdchi9ut6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterNewApp3',
  );
}
